[package]
name = "terms"
version = "0.1.0"
authors = ["Dirk Van Haerenborgh <vhdirk@gmail.com>"]
edition = "2021"

[profile.release]
lto = true

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0.126", features = ["derive"] }
once_cell = "1.13.0"
async-channel = "2.1.1"

glib = { version = "^0.18" }
gio = { version = "^0.18" }
pango = { version = "^0.18" }
gdk = { package = "gdk4", version = "^0.7", features = ["v4_12"] }
gtk = { package = "gtk4", version = "^0.7", features = ["v4_12"] }

adw = { package = "libadwaita", version = "0.5", features = ["v1_4"] }
panel = { package = "libpanel", version = "0.3" }
vte = { git = "https://gitlab.gnome.org/vhdirk/vte4-rs", package = "vte4", branch = "0.7", version = "0.7", features = [
    "v0_72",
] }
ashpd = { git = "https://github.com/bilelmoussaoui/ashpd.git", version = "0.7.0" }
rsvg = { package = "librsvg", version = "2.57" }
gsettings-macro = "0.1.20"

async-std = "1.12.0"
shell-quote = "0.5.0"
constcat = "0.4.0"

serde_with = "3.4.0"
ref_thread_local = "0.1.1"
dirs = "5.0.1"
serde_json = "1.0.111"
rand = "0.8.5"
elementtree = "1.2.3"
serde_yaml = "0.9.30"
itertools = "0.12.0"

[build-dependencies]
glib-build-tools = "0.18.0"
