[package]
name = "terms"
version = "0.1.0"
authors = ["Dirk Van Haerenborgh <vhdirk@gmail.com>"]
edition = "2021"

[profile.release]
lto = true

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = "0.3"
serde = { version = "1.0.194", features = ["derive"] }
once_cell = "1.13.0"
async-channel = "2.1.1"

glib = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.18", branch = "0.18" }
gio = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.18", branch = "0.18"  }
pango = { git = "https://github.com/gtk-rs/gtk-rs-core", version = "0.18", branch = "0.18"  }
gdk = { git = "https://github.com/gtk-rs/gtk4-rs", package = "gdk4", version = "0.7", branch = "0.7", features = ["v4_6"]}
gtk = { git = "https://github.com/gtk-rs/gtk4-rs", package = "gtk4", version = "0.7", branch = "0.7"  }

adw = { git = "https://gitlab.gnome.org/World/Rust/libadwaita-rs", package = "libadwaita", version = "0.5", branch = "v0.5", features = ["v1_4"] }
panel = { git = "https://gitlab.gnome.org/World/Rust/libpanel-rs", package = "libpanel", version="0.3", branch="v0.3"}
vte = { git = "https://gitlab.gnome.org/World/Rust/vte4-rs", package = "vte4", version = "0.7", branch = "0.7", features=["v0_70"]  }
async-std = "1.12.0"
shell-quote = "0.5.0"
constcat = "0.4.0"
gsettings-macro = "0.1.20"

[build-dependencies]
glib-build-tools = "0.18.0"

