edition = "2021"
max_width = 160
hard_tabs = false
match_block_trailing_comma = true
merge_derives = true
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = true
