edition = "2021"
max_width = 80
hard_tabs = true
match_block_trailing_comma = true
merge_derives = true
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
tab_spaces = 2
use_field_init_shorthand = true
