[build]
rustflags = ["--cfg", "ruma_identifiers_storage=\"Arc\""]

[env]
GSETTINGS_SCHEMA_DIR = { value = "target", relative = true }
GETTEXT_PACKAGE = "terms"
APP_ID = "com.github.vhdirk.Terms"


[doc.extern-map.registries]
crates-io = "https://docs.rs/"

