[build]
# stuff for mold linker
rustflags = ["--cfg", "ruma_identifiers_storage=\"Arc\""]

[env]
GSETTINGS_SCHEMA_DIR = { value = "target", relative = true }
GETTEXT_PACKAGE = "terms"
APP_ID = "io.github.vhdirk.Terms.Devel"
PROFILE = "Devel"

