on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]

name: CI

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - name: Create blank versions of configured file
        run: echo -e "" >> src/config.rs
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  build:
    name: check
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    env:
      DISPLAY: ":99.0"
    steps:
      - name: Install dependencies
        run: |
          yum install -y \
            gtk4-devel \
            libadwaita-devel \
            libpanel-devel \
            gtksourceview5-devel \
            poppler-glib-devel

      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy

      - name: Clippy
        run: cargo clippy -- --deny warnings

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: my-terms.flatpak
        manifest-path: build-aux/io.github.vhdirk.Terms.Devel.json
        run-tests: true
        cache-key: flatpak-builder-${{ github.sha }}
